### ISSUE TITLE
Selection not working correctly on touch device

### ISSUE THREAD

**Issue by diogeneshamilton** [webscopeio/react-textarea-autocomplete#102]
Version: 3.1.1
Video recorded on iOS Simulator (so these clicks are actually Touch events)
![bug 1](https://user-images.githubusercontent.com/983876/48729733-4d8f5c80-ec06-11e8-8665-d19483afb523.gif)

I believe this may have been introduced in this PR: https://github.com/webscopeio/react-textarea-autocomplete/pull/90 

It may be alleviated by adding onTouchStart as the same as the OnClick handler.

EDIT: Downgrading to v2.3.5 fixes this issue, so something after that must have introduced it.

**Comment by jukben** [comment]
Hey Matthew!

Thanks for the ☕️, you are the best! ❤️ I'll take a look on this, I believe it might be easy fix.

**Comment by jukben** [comment]
May I ask you which simulator do you use? I've just tried the default project (you can clone the repo and do `yarn dev`) on iPhone XR 12.1 and everything (I mean, the viewport is not responsive, but) works fine. You can click on the item, the item gets replaced and autocomplete is closed.

**Comment by jukben** [comment]
Hey. You are right `onStartTouch` solved the issue in my case. Could you try it in your scenario? I've just deployed v3.1.2 🙏

**Comment by diogeneshamilton** [comment]
Thanks! I've been testing, and unfortunately it doesn't work flawlessly in my case since it's a scrollview. I've been working on finding a fix, but the logic around selecting an item (and what closes the autocomplete) has prevented me from finding the perfect one yet. I can work on this a bit today though. Thanks for your help!

**Comment by diogeneshamilton** [comment]
Looks like I was able to fix my issues by essentially tracking touches on the list items: 

```
            onTouchStart={(e) => { 
            	this.clicked = true
            	this.selectItem(e)
            }}
            onTouchEnd={(e) => { 
            	if (this.clicked) {
            		onClickHandler(e)
            	}
            }}
            onTouchMove={(e) => { 
            	this.clicked = false
            }}, 
            onTouchCancel={(e) => { 
            	this.clicked = false
            }}
```

Not sure if this is the most elegant solution, but maybe more complete for all touch cases. For now I'll downgrade to 2.3.5 for my production app (or use a doctored version with this fix), but let me know what you end up going with. I'm happy to submit a PR too if that's easier.

**Comment by rrikesh** [comment]
I'm also having this issue on iOS Safari on the emoji example, I'm using version 3.1.2

**Comment by jukben** [comment]
Yeah, @rrikesh I guess the solution by @diogeneshamilton might solve it. Are you able to test it and send PR? Otherwise, I might have time for it during the weekend. 🚀

**Comment by rrikesh** [comment]
I tried @diogeneshamilton's fix but didn't work. Or maybe I am doing something wrong. I'll try to dig in the code again during the day. I'll send a PR if I manage to fix it.

**Comment by rrikesh** [comment]
I sent a PR based on @diogeneshamilton's fix. I tested on iOS only.

**Comment by rrikesh** [comment]
Tested on Android too! All good on my side!

**Comment by diogeneshamilton** [comment]
Absolute win!!! Thank you @rrikesh!!!

**Comment by jukben** [comment]
Thanks to both of you! Should be ready in 3.1.4 (along with perf fix). 🚀
