### ISSUE TITLE
Output function fires a lot

### ISSUE THREAD

**Issue by guidogast** [webscopeio/react-textarea-autocomplete#104]
I noticed that the output function is firing a lot. Check out this pen, open the console and start triggering the auto complete: https://codepen.io/dagorbattle/pen/rQYZzj 

It looks like 1 change (also a change of the selected item) triggers the output function 14 times. It looks like this is unwanted behavior.

**Comment by jukben** [comment]
Fixed, and released as 3.1.4! 🚀
