### ISSUE TITLE
Prevent form submission on Enter when autocomplete is open

### ISSUE THREAD

**Issue by O4epegb** [webscopeio/react-textarea-autocomplete#112]
Is it possible to prevent form submission on Enter key press when autocomplete is open?

I couldn't find a way or hack to do this! Basically it means that form submits instead of selecting needed autocomplete value. I know that you can press Tab to autocomplete but Enter is more intuitive I think and most users press enter when selecting autocomplete suggestions.

Would be cool to have a prop to block event propagation, or maybe some state callback so you could stop submission by yourself if autocomplete is open.

What do you think?

P.S. did not tried v.4 yet, maybe it is possible there?

**Comment by jukben** [comment]
Hey, could you please prepare repro on codepen (based on this https://codepen.io/jukben/pen/bYZqvR). It sounds like something worth to fix. 👍

**Comment by jukben** [comment]
I see that's an actually great point. I've prepared a PR for it.

**Comment by O4epegb** [comment]
Oh, I am sorry, was on vacation, coulndt check!

Very cool, that is exactly what I needed, thank you very much! :) Gonna test new version this week

**Comment by jukben** [comment]
No problem @O4epegb I hope you've enjoyed it!
