### ISSUE TITLE
Escape key is not propagated when autocomplete is closed

### ISSUE THREAD

**Issue by O4epegb** [webscopeio/react-textarea-autocomplete#116]
Escape key is not propagated when autocomplete is closed.

I think it might be because there is 2 listeners for Escape in `Textarea.jsx` and second one is never destroyed.

This one is probably unnecessary
https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L254

**Comment by O4epegb** [comment]
If that is the case I might make a PR :)

**Comment by jukben** [comment]
Oh, sorry, wrong rebase, you are right!

**Comment by jukben** [comment]
Could you please push PR for it? 👍

**Comment by O4epegb** [comment]
Sure, going to make it!

**Comment by jukben** [comment]
Closed in #118. Thanks for that!
