### ISSUE TITLE
Minified React error #185

### ISSUE THREAD

**Issue by jukben** [webscopeio/react-textarea-autocomplete#125]
Hey guys, do you know when you release your great fix ? A user of my app just told me that her page crashed and I just figured out that she had this in the console:
![bug_charlie](https://user-images.githubusercontent.com/32838942/51838946-0f01d680-2308-11e9-987d-5538d0081ba9.PNG)

Do you confirm that it is on your side ? I'll just wait for the fix :)

_Originally posted by @BenoKop in https://github.com/webscopeio/react-textarea-autocomplete/issues/124#issuecomment-458129724_

**Comment by jukben** [comment]
Hey @BenoKop, what version are you using? This could be also because of possible recursion here https://github.com/webscopeio/react-textarea-autocomplete/commit/3f822ab91859cf192b155a2cf0cd359f0ae3d3e8 We're preparing fix for that as a part of #124 

Is this error also platform/user specifics? Are you able to reproduce it on your machine with dev mode enabled?

**Comment by BenoKop** [comment]
Hey @jukben ! I'm using the 4.1.0 version.
In my case, I was able to reproduce de bug on dev mode only on Chrome.

What I get
![bug_textarea1](https://user-images.githubusercontent.com/32838942/51841727-8d15ab80-230f-11e9-94ab-8dd10e26c46b.PNG)
![bug_textarea2](https://user-images.githubusercontent.com/32838942/51841728-8edf6f00-230f-11e9-971e-a05a864a5b28.PNG)

This is the extreme bottom of my page. I have Textarea which the users can tag other users.
It is only crashing when I start to write AFTER the marker (@) AND on the second line of my textarea.
![charlie_bot](https://user-images.githubusercontent.com/32838942/51842014-3ceb1900-2310-11e9-820a-13cee8df9f6a.PNG)

In this case, if i continue to type, it will crash. Hope it helps !

**Comment by jukben** [comment]
I see, that's exactly the issue @andypearson going to address in his PR solving this bug and the behavior in general. So sorry about that, the best what you can do to prevent it is to downgrade to 4.0.0.

**Comment by jukben** [comment]
Deployed as 4.2.3! 🚀

**Comment by BenoKop** [comment]
Nice work !
Tried it and updated my app !
