### ISSUE TITLE
drop down blocks text typed.

### ISSUE THREAD

**Issue by japrogramer** [webscopeio/react-textarea-autocomplete#131]
after the trigger causes the dropdown to show
the actual dropdown element cuts off the text after by about half

![Line height not accounted for](https://user-images.githubusercontent.com/1387859/52528306-2e521980-2ca1-11e9-95e2-2a8bf90a0064.png)

I suggest that we take into account the elements line height , the random hovering button 
is a firefox bug.

![suggested change](https://user-images.githubusercontent.com/1387859/52528317-a6204400-2ca1-11e9-8d1f-34b9de14333c.png)

something like so 
```
function isDigit(charCode: number): boolean {
    return charCode >= CHAR_CODE_ZERO && charCode <= CHAR_CODE_NINE
}

export function getLineHeightPx(node: HTMLElement): number {
  const computedStyle = window.getComputedStyle(node)

  // If the char code starts with a digit, it is either a value in pixels,
  // or unitless, as per:
  // https://drafts.csswg.org/css2/visudet.html#propdef-line-height
  // https://drafts.csswg.org/css2/cascade.html#computed-value
  if (isDigit(computedStyle.lineHeight.charCodeAt(0))) {
    // In real browsers the value is *always* in pixels, even for unit-less
    // line-heights. However, we still check as per the spec.
    if (
      isDigit(
        computedStyle.lineHeight.charCodeAt(
          computedStyle.lineHeight.length - 1,
        ),
      )
    ) {
      return (
        parseFloat(computedStyle.lineHeight) *
        parseFloat(computedStyle.fontSize)
      )
    } else {
      return parseFloat(computedStyle.lineHeight)
    }
  }
}

```

**Comment by jukben** [comment]
I'm not planning to do any too clever logic about this. The all you need is to tweak styles bounded to `rta__autocomplete` class to suit your case.

**Comment by japrogramer** [comment]
I tried to use the dropdownStyle but it seems that the position top and bottom are passed to Autocomplete are computed on the componentDidUpdate so there is no way to change the top bottom like that.


dropdownStyle={{zIndex: 2, top, bottom}}

**Comment by jukben** [comment]
Yep. That's correct. You should use `margin` https://github.com/webscopeio/react-textarea-autocomplete/blob/master/style.css#L29
