### ISSUE TITLE
Prevent output

### ISSUE THREAD

**Issue by saumitra171** [webscopeio/react-textarea-autocomplete#132]
Is it possible to prevent outputting to textarea for certain items ?

My use case is, I want to show a popup on selection of certain types of items and then when the popup is dismissed I want to update the textarea based on user action.

**Comment by jukben** [comment]
I'm not sure if I can understand this part

> then when the popup is dismissed I want to update the textarea based on user action.

Do you want to take action based on dismissed popup? (not selected item?)

Could you please create a codepen (fork of this https://codepen.io/jukben/pen/bYZqvR) with steps to reproduce?

**Comment by saumitra171** [comment]
Please checkout the comments
https://codepen.io/smtrd/pen/WPyjag?editors=0010

**Comment by jukben** [comment]
Hey, I think it's a valid point and in this case, we should support returning `null`. I will try to hack something so stay tuned!

**Comment by jukben** [comment]
Deployed in 4.3.0 🚀
