### ISSUE TITLE
Escape key is not propagated sometimes

### ISSUE THREAD

**Issue by O4epegb** [webscopeio/react-textarea-autocomplete#135]
So, escape key propagation stops after autocomplete is shown first time.

Steps to reproduce: (for example here https://874-94480675-gh.circle-artifacts.com/0/example/index.html)
1) Press Escape. In console there will be log indicating that Escape was pressed
2) Type "@" to trigger autocomplete, then select value
3) Press Escape again, now there is no console log, because it is not propagating

It seems that every time you trigger autocomplete popup, one listener for Escape key is added (to prevent propagation), but after popup is closed listener is not removed for some reason. So if you trigger popup 10 times there will be 10 listeners still alive. I cannot figure out why, because [this](https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L231) code seems to work and it actually trying to remove listeners after popup is closed. But it doesn't work for some reason.

**Comment by O4epegb** [comment]
I think I got it!

It might be because of this block inside listener code

```
    this.listeners[this.index] = {
      keyCode,
      fn
    };

    this.index += 1;

    return this.index;
```

So for example, when we add first listener the index starts with 0. We add it to hashmap of listeners, but then we increment index to 1 and return it (that a bug, we should return 0). So when we try to delete we actually deleting wrong listener every time.

**Comment by O4epegb** [comment]
It is actually quite strange pattern to use (indexes), maybe we should refactor it to more common pub sub implementation with just function references?

**Comment by jukben** [comment]
Oh, that makes sense. It should be `return this.index++;` or something if I'm correct. But definitely, I'm for refactoring it. Will you give it a shot?

**Comment by O4epegb** [comment]
Yep! I think I will do fast fix like `return this.index++;` and maybe refactor afterwards!

**Comment by jukben** [comment]
Yeah, the quick fix is an OK solution for now! Thanks for this. Once you test it out that it works for your use case, please create a PR. I will merge it ASAP. Thanks for letting me know! 💪
