### ISSUE TITLE
Can you please specify the Browser versions you support?

### ISSUE THREAD

**Issue by afsal008** [webscopeio/react-textarea-autocomplete#137]
Cannot understand from the wording Last 2 Versions

**Comment by jukben** [comment]
What exactly you can't understand? We are targeting to support the last 2 version of specified browsers.

**Comment by afsal008** [comment]
That means, there is no assurance that this supports from a specific version.

**Comment by jukben** [comment]
Yeah. But generally, it's meant to be working for all browsers from IE11 up. I'm not saying it's perfect in IE11, but it's working somehow. If you find out that for some browser it's not working, we will consider the severity and we might end up fixing it. 

The Readme is here just for a quick overview, it's gonna work in every "normal" browser I guess. 

Thanks for asking I hope I solve the issue.
