### ISSUE TITLE
Suggestion list doesn't appear again after pressing keydown button

### ISSUE THREAD

**Issue by jazzy-em** [webscopeio/react-textarea-autocomplete#138]
Hello! Thanks for awesome component your built!

I faced with issue which is reproducable on [demo example](https://codepen.io/jukben/pen/bYZqvR)

**Steps:**
1. Type :s. Suggestion list appears
2. Press keydown button on keyboard
3. Type one more char

**Expected behavior:**
Suggestion list appears after typing new char

**Actual behavior:**
Suggestion list doesn't appear any more until you delete all chars before trigger symbol

**Comment by jukben** [comment]
Thanks for the issue! It was a quick fix, right now I'm working on e2e test to prevent such a regression in the future. 🙌 I'm gonna deploy fixed version today. 🚀

**Comment by jukben** [comment]
Bugfix has been prepared if you have time, you can check it out! #139

**Comment by jazzy-em** [comment]
Thanks for so quick response and fix! I've checked it, it works as expected. Thanks!

**Comment by jukben** [comment]
Deployed as 4.3.2 🚀
