### ISSUE TITLE
can not load css auto

### ISSUE THREAD

**Issue by fuzhengsong** [webscopeio/react-textarea-autocomplete#140]
style.css is not load when i import react-textarea-autocomplete
![image](https://user-images.githubusercontent.com/25757269/53475408-cf670f80-3aaa-11e9-9fb2-8f53a5ba46d6.png)

**Comment by danieljaguiar** [comment]
Did you find a solution @fuzhengsong ?

**Comment by danieljaguiar** [comment]
Never mind =)

`import "@webscopeio/react-textarea-autocomplete/style.css";`
