### ISSUE TITLE
update textarea content

### ISSUE THREAD

**Issue by dragon-15** [webscopeio/react-textarea-autocomplete#141]
Cant figure out how to update the value of textarea from function.

**Comment by jukben** [comment]
Hey, check it out the playground implementation 

Live: https://874-94480675-gh.circle-artifacts.com/0/example/index.html
Code: https://raw.githubusercontent.com/webscopeio/react-textarea-autocomplete/master/example/App.jsx

For example check it out an implementation of "Change value to ":troph". Is it clear?

If not can you please specify more what are you trying to do and maybe create some Codepen with steps to reproduce?

**Comment by dragon-15** [comment]
Not working for me, I've updated the codepen provided by you in demo.

https://codepen.io/anon/pen/LaZVWP

**Comment by jukben** [comment]
The demo is wrong, it has to be inside of React's life cycle using `setState` for example.

**Comment by dragon-15** [comment]
I've updated the demo and used setstate.

https://codepen.io/anon/pen/LaZVWP

**Comment by jukben** [comment]
Hey, I need some additional context @dragon-15. How are you using this component as UMD module? Check it out this https://codesandbox.io/s/k34153yp0v. It seems to work there.
