### ISSUE TITLE
ROWS

### ISSUE THREAD

**Issue by apenab** [webscopeio/react-textarea-autocomplete#143]
I have the same problem and would like to have this functionality => [Problems with Min ROWS](https://github.com/signavio/react-mentions/issues/292)

**Comment by jukben** [comment]
Rows should be supported by default, everything is passed by `textarea`. The issue you might have is that `height` defined in CSS you are loading if you are using default css provided by RTA.

**Comment by apenab** [comment]
I use this package => [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize), in which I can use the `minRows` property, when I use your package I do not find homogenity with my other textarea

**Comment by jukben** [comment]
Could you please create repro? I've checked it out the implementation of react-textarea-autosize, it looks like minRows is just argument during height computation. So it could clash with RTA defaults CSS styles.

**Comment by jukben** [comment]
Not planing to provide any extra support for this, so I'm closing it
