### ISSUE TITLE
Show popup at a new line when afterWhitespace is set to true

### ISSUE THREAD

**Issue by Psyphant** [webscopeio/react-textarea-autocomplete#147]
Hey!
Is it possible to trigger the autocomplete also on a new line when **afterWhitespace** is set to **true**?

Steps to reproduce:
1. Hit enter
2. Type @

https://codesandbox.io/embed/2v6q1rqry0

**Comment by jukben** [comment]
Hey! You probably want to use `minChar` prop. 

minChar={0} does the trick

**Comment by jukben** [comment]
Hey!

Yep. Sorry about that, another bug. We should look for any white character not just for " ".

**Comment by Psyphant** [comment]
Sorry for the delay ... I created an PR with your above mentioned solution and it works like a charm 👍

**Comment by jukben** [comment]
Awesome! Released as 4.3.5! 🚀 Thanks!
