### ISSUE TITLE
Please provide value on select

### ISSUE THREAD

**Issue by TomClarkson** [webscopeio/react-textarea-autocomplete#15]
Can you please call onChange with the value after an item is selected. I think instead of calling onChange with the change event it would be better to call it with the value in both places.

https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L122

**Comment by jukben** [comment]
Yeah, it makes sense. I'm just wondering If I have to call onChange with the `event` instance, or simply with an object. What do you think? @TomClarkson 

Anyway, thanks for the interest in it. It makes me happy! 🤓

**Comment by jukben** [comment]
I think it's good to be consistent with the normal `textarea` API. I expecting that the parameter of onChange would be an `event` object. What about to introduce another handler `onItemChange`, which will provide the currently selected item. Otherwise, it will be the breaking change.

**Comment by TomClarkson** [comment]
Yeah onItemChange will work 😄  

My use case is I need to update the display on an item when someone is typing in a form so I need the live value of the text input.

**Comment by jukben** [comment]
Ok, I will go for `onChangeItem: (selectedItem) => void`.

Anyway I don't don't follow properly to your use case. How would this help in a case of providing "the live value of the text input"? Could you please try it again? Every use case could help to understand how people want to use it.

**Comment by jukben** [comment]
I see it's actually bug! Good catch. The `onChange` is not triggered after selection. Thanks, stay tuned for the new version.

**Comment by jukben** [comment]
Fixed in version v1.1.2. Please, check it out. @TomClarkson
