### ISSUE TITLE
Set a predefined value inside the textarea

### ISSUE THREAD

**Issue by Psyphant** [webscopeio/react-textarea-autocomplete#151]
Hey @jukben,

I wanna set a predefined value (autosave feature) for the textarea.

It's not possible to set the value directly like `<ReactTextareaAutocomplete value={"test"} ... /> ` because from then on you can't change the text at the textarea by typing anymore.

In #141 you mentioned it's the best way to change the value of the component ( `<ReactTextareaAutocomplete value={text} ... />`) via `this.state.text` and `setState({text: value})`.

So I use setState in the componentDidMount() function (recommended here: https://itnext.io/react-setstate-usage-and-gotchas-ac10b4e03d60) and I get everytime the same error:

`Uncaught TypeError: Cannot read property 'selectionEnd' of null
    at ReactTextareaAutocomplete._this2._changeHandler (react-textarea-autocomplete.es.js:1028)
    at ReactTextareaAutocomplete.componentDidUpdate (react-textarea-autocomplete.es.js:1287)
    at commitLifeCycles (react-dom.development.js:17349)
    at commitAllLifeCycles (react-dom.development.js:18736)`

The problem is probably the triggered custom "change" event, which has no target.

The component is at this time not visible in the DOM. Is this the real problem?

**Comment by Psyphant** [comment]
It's probably not an issue of your component. I need to figure out, who is bubbling the custom change event, which has no target.

**Comment by jukben** [comment]
If you will figure out what might be an issue, or how to prevent it, feel free to post it here, please 🙏

**Comment by Psyphant** [comment]
The problem appears when you try to change the value of a textarea (for example via redux) but addresses more than one textarea by mistake (every textarea needs a clear identifier).
