### ISSUE TITLE
selected property for entire item

### ISSUE THREAD

**Issue by Daniele122898** [webscopeio/react-textarea-autocomplete#153]
So i saw that there is a selected style when you use the arrow keys so i can change the color. But as you can see it only works for the entity. There seems to be no such thing for the entire item like on the hover event as seen above.

![image](https://user-images.githubusercontent.com/20451770/58271305-0e47f100-7d8c-11e9-8e2b-891a8955159a.png)

Is there a way so that i can change the color of the entire item with the selected function or is that planned?

**Comment by jukben** [comment]
You should be able to style it with `.rta__entity--selected` css selectors

**Comment by Daniele122898** [comment]
it doesnt seem to work for some reason. when i hover over it, everything turns purple. But when i use the arrow keys only the inside changes color using the `.rta__entity--selected` class. I need the entire item to change color but there is no `.rta__item--selected` class

**Comment by jukben** [comment]
Ah, I follow know. You're correct. Let's add class also for item then, are you willing to sent PR for it? 

https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Item.jsx#L40

**Comment by Daniele122898** [comment]
i can try sure :)

**Comment by O4epegb** [comment]
I think this could be closed now!)

**Comment by jukben** [comment]
Closed in 6b5296499d503f540b31089521134b80b610141a
