### ISSUE TITLE
Listener doesn't work after first unmount of Textarea

### ISSUE THREAD

**Issue by JokerNN** [webscopeio/react-textarea-autocomplete#16]
Hello, first of all thanks for your library

I faced an issue while using this.
After first unmount of Textarea main component list navigation with keys becomes impossible.
It happens because Textarea.jsx calls `removeAll` here https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L92

Which removes `keydown` event listener forever (until page refresh).
Next mounts of Textarea components won't work properly.

I fixed it roughly here https://github.com/webscopeio/react-textarea-autocomplete/compare/master...JokerNN:master

This change effectively means that `keydown` event listener will persist forever. (downside of global singletone listener)

I will get rid of it in PR

**Comment by jukben** [comment]
Hi,

thanks for feedback and issue reports. I'll also look on it, I wasn't aware of this behavior. 

Anyway PR is welcomed!

**Comment by jukben** [comment]
Closed by #16
