### ISSUE TITLE
style property in file textarea-caret maybe wrong

### ISSUE THREAD

**Issue by fuzhengsong** [webscopeio/react-textarea-autocomplete#164]
The component Autocomplete is not at correct position when textarea value is long.I found the style in textarea-caret should be "wordBreak" not "wordWrap".

**Comment by jukben** [comment]
Could you please create repo somewhere? You can use this "template": [codesandbox](https://codesandbox.io/s/k34153yp0v), [codepen](https://codepen.io/jukben/pen/bYZqvR).
