### ISSUE TITLE
Bug. Problems with trigger if it does not consist of one character. Like in #145 issue. 

### ISSUE THREAD

**Issue by OlegVach** [webscopeio/react-textarea-autocomplete#167]
Problem with triggers. I am using 3 different triggers. "@", ":", "{{". Trigger "{{" doesn't work correctly. It shows dropdown list only after another triggers. If you try print this trigger it doesn't works.

**Comment by jukben** [comment]
Could you please provide steps to reproduce and expected result? 

You can use this codesandbox, just tweak it for your use-case: https://codesandbox.io/s/vjx16

**Comment by OlegVach** [comment]
Try it. https://codesandbox.io/embed/ancient-sun-ysz9k
Try set at first this symbols "{{". It will be not showing dropdown.
When you set this ";" at first, and after this "{{" it will be working.
