### ISSUE TITLE
Autocomplete option is not applied when clicked on IE11

### ISSUE THREAD

**Issue by aklxx100** [webscopeio/react-textarea-autocomplete#171]
**Version**: `^4.6.0`
**Browser**: `Internet Explorer 11.829.17134.0`
**OS**: `Windows 10 Pro`

## Current state - Defect/Bug
On IE 11, the autocomplete option is not applied (appended in the textarea) when clicked (mouse).

## Expected state
The autocomplete option is applied (appended in the textarea) when clicked (mouse) as in using  IE Edge, Chrome and Firefox.

**Comment by jukben** [comment]
Hey, thanks for the issue, I've been able to reproduce it – it's only related to clicking tho. Interesting, should be quite easy to fix.

**Comment by jukben** [comment]
Hey, should be fixed in 4.6.1! Let me know! 🚀

**Comment by aklxx100** [comment]
Tested and passed! Thanks!
