### ISSUE TITLE
onBlur triggered when focusing on <textarea>

### ISSUE THREAD

**Issue by dhruvparmar372** [webscopeio/react-textarea-autocomplete#178]
I'm trying to use `onFocus` & `onBlur` events. It seem the `onBlur` event is triggered even when focusing on the `<textarea` element. Here is a codesandbox showing the behavior
https://codesandbox.io/s/sharp-bird-ld8r4

**Comment by jukben** [comment]
Thanks a lot for the issue, it really look as a bug – appreciated the codesandbox! I'll take a look ASAP.

**Comment by tgroutars** [comment]
Any news on this?

**Comment by jukben** [comment]
@tgroutars Thanks for reminder, I just fixed that. Released as [4.6.2](https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v4.6.2). Enjoy and start the library ⭐️
