### ISSUE TITLE
Consider deprecation in favor or @signavio/react-mentions

### ISSUE THREAD

**Issue by jukben** [webscopeio/react-textarea-autocomplete#179]
https://github.com/signavio/react-mentions looks awesome and it might be sufficient for the most of the scenarios folks are using this library.

**Comment by ctsimpouris** [comment]
I disagree. https://github.com/signavio/react-mentions provides better initial styling but lacks in functionality. For example, you cannot provide with custom input component (while `textAreaComponent` provides more power).
