### ISSUE TITLE
Trigger output does nothing in case of string-based items

### ISSUE THREAD

**Issue by milosimr** [webscopeio/react-textarea-autocomplete#19]
Hi,

I'm having issues with configuring trigger output, whatever I put in that function, all I get as a result is the value of selected item. My guess is that output field gets ignored when I assign trigger prop.

Here's the code:

```javascript
          <ReactTextareaAutocomplete
            className="ant-select-auto-complete.ant-select ant-input"
            loadingComponent={Spin}
            trigger={{
              '#': {
                dataProvider: (token) => {
                  if (!token || !token.length) {
                    return this.allProperties
                  }
                  return this.allProperties.filter(prop => {
                    if (prop.search(new RegExp(token, "i")) !== -1) {
                      return prop
                    }
                    return null
                  })
                },
                component: ItemComponent,
                output: (item, trigger) => `#${item}#`
                },
              },
            }}
          />
```

Thanks

**Comment by jukben** [comment]
Just for to be sure, could you please provide your `ItemComponent` an example of data which provides `dataProvider`?

The value which returns `output` function will replace the current text which has trigged a suggestion. 

Example:

```js
const ItemComponent = props => {
  console.log(props);
  return <div>{props.entity.text}</div>;
};

const Loading = ({ data }) => <div>Loading</div>;

<ReactTextareaAutocomplete
  className="ant-select-auto-complete.ant-select ant-input"
  loadingComponent={Loading}
  trigger={{
    ":": {
      dataProvider: token => {
        return [{ id: 1, text: "👋" }, { id: 2, text: "🙌" }];
      },
      component: ItemComponent,
      output: (item, trigger) => {
        return `:${{
          "👋": "hello",
          "🙌": "praise"
        }[item.text]}:`;
      }
    }
  }}
/>;
```

**Comment by milosimr** [comment]
Not sure I understand. `dataProvider` or in this case `this.allProperties` for me is a list of strings.

Therefore my item component is:
```javascript
const ItemComponent = props => (<div>{props.entity}</div>)
``` 

Just to clarify, when I select a value, for instance `LIDAR_Falldist`, as a result I get `#LIDAR_Falldist` and output function isn't called at all, where according to documentation I should get `#LIDAR_Falldist#`, or whatever I put there?

Thanks for the quick reply

**Comment by jukben** [comment]
I see! You are right. That's, unfortunately, a bug. I'll send a fix for it later today. 

Thanks again for discovering it! 🙏

**Comment by jukben** [comment]
Anway, @milosimr I'm wondering what do you say about to change a default behavior of `output`  function for the string based item to `<current-trigger-char>item<current-trigger-char>`. I personally think that it will be better. I would introduce it as a breaking change.

**Comment by milosimr** [comment]
@jukben Is this a bug with string values only? I do have these properties in a list of objects, and will use it eventually, since I plan on rendering different options depending on property type. 

As for inserting I actually need to insert a query, more like 'property in('some value', 'another value') etc, I was using trigger chars just for testing, but yeah I can see how wrapping the value in trigger chars will be more useful.

Speaking about improvements, is there a way to display a list of values right after we insert a trigger char? If that's a bigger change I could work on it in the next few days...

**Comment by jukben** [comment]
@milosimr The bug that you found only affecting the string-based items. For object-based items you have to define output function and it's just fine (see my example above).

> Speaking about improvements, is there a way to display a list of values right after we insert a trigger char? If that's a bigger change I could work on it in the next few days...

This is not currently possible. But I like your idea. What about to introduce optional param, let's say `minChar: integer` with default: 1, number of character you have to type to trigger the autocomplete suggestion?

**Comment by milosimr** [comment]
@jukben I got it to work with objects. Thanks.

> This is not currently possible. But I like your idea. What about to introduce optional param, let's say minChar: integer with default: 1, number of character you have to type to trigger the autocomplete suggestion?

Yeah, that sounds good. If I get the time the next couple of days, will look into implementing it.

**Comment by jukben** [comment]
Hey @milosimr, I was kinda bored so I fix the issue and I've added the new `minChar` prop. So you could use it like `minChar={0}` for your case. I've hope you like it!

🎉 1.2.0
`yarn add @webscopeio/react-textarea-autocomplete` 

Anyway if you figure out something else, feel free to propose it. Also about docs, if something was unclear, please feel free to send PR for changes. I'd appreciate it.

**Comment by milosimr** [comment]
@jukben Thanks man, you're great.

Another thing that would be nice to have is ability to position the cursor in the output string. I don't have an idea how that would be achieved though...

**Comment by jukben** [comment]
@milosimr I'm glad I was able to help. If you like the package, please ⭐️  it, it means a lot for us.

So you mean something like you want to specify where will be caret after user select item from suggestion box? We could handle this. Options could be `string: "start", "end" or position: "integer"` (position in the final string). What do you think?
