### ISSUE TITLE
allowWhitespace breaks search trigger

### ISSUE THREAD

**Issue by haveanicedavid** [webscopeio/react-textarea-autocomplete#194]
![demo](http://g.recordit.co/VCNLojs4r9.gif)

In the above, I have two triggers. One for `((` (which allows whitespace), one for `#` (which does not). You can see when I type the `((` trigger, additional input doesn't update the search, whereas using `#` it updates appropriately 

When whitespaces are allowed, the dataProvider doesn't seem to be making subsequent search calls after the initial letter is entered. 

Code in case it's relevant:
```
    '((': {
      allowWhitespace: true,
      dataProvider: async (token: string) => {
        const text = token.substr(1)
        const result = await searchBlocks(text)
        const parsed = result.map(({ text, id }) => {
          return { text, id }
        })
        return parsed
      },
      component: BlockItem,
      output: (item: any) => `((${item.id}))`,
    },
```

I can probably come up with a workaround, but still seems worth filling. Do I have something set up incorrectly?

Loving the package otherwise! Works great

**Comment by jukben** [comment]
Hey, thanks for the issue report. I'm afraid that this might be bug in `allowWhitespace` implementation 😞. As I remember the implementation is very clumsy. However, I won't find time to fix it anytime soon – you can try your luck tho.

**Comment by jukben** [comment]
Haha, I spent 10 mins just to double check what's the expected behavior and I realized that you are responsible for doing that "search" logic within `dataProvider` implementation. So I guess if you do something like:

```tsx
const parsed = result.map(({ text, id }) => {
          return { text, id }
        }).filter(...)
```

It should work just fine. Can you try it?

**Comment by haveanicedavid** [comment]
I'm not sure I'm following. I can change the logic within the `dataProvider`, however the core issue is that the provider only seems to be called once - on initial text input. So in the gif, it picks up the initial `a`, but no subsequent characters - putting a console log in like this:
```
    '((': {
      allowWhitespace: true,
      dataProvider: async (token: string) => {
        console.log('token :>> ', token)
        return ['hello']
      },
      component: BlockItem,
      output: (item: any) => `((${item.id}))`,
    },
```
... only fires `token` once.

I'll try to dig into it a bit later this weekend

**Comment by jukben** [comment]
You are right. I was able to reproduce it. I will try to find time to look at it.

**Comment by jukben** [comment]
I was able to find out that this issue emerges when you use multichar trigger like `((`

**Comment by jukben** [comment]
Deployed fix in https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v4.7.1 

Please, test it if it works for your use-case and enjoy. 🚀

**Comment by haveanicedavid** [comment]
Apologies for a very delayed reply - I'm normally good at checking git notifications but missed this!

I actually switched to use a different library for my feature but ultimately circled back to yours after that route was causing way more of a headache - your fix works perfectly! 

Loving the library. Thank you 🙏
