### ISSUE TITLE
Remove the debug (?) console output from production code

### ISSUE THREAD

**Issue by davidmz** [webscopeio/react-textarea-autocomplete#202]
This line: https://github.com/webscopeio/react-textarea-autocomplete/blob/dd32e095dfebf4a589a9d07027d8efe7bf067746/src/Textarea.jsx#L664 prints console message on each component initialization.

**Comment by jukben** [comment]
Great catch, I prepared a PR so get rid of it ASAP. Next time feel free to send PR as well! 🙏
