### ISSUE TITLE
Allow empty text in output functor

### ISSUE THREAD

**Issue by anukul** [webscopeio/react-textarea-autocomplete#211]
```js
output: (item, trigger) => ({
  text: '',
  caretPosition: 'start',
}),
```
This fails because [this](https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L533) throws an error when text is `''`:
```js
if (!textToReplace.text) {
  throw new Error(
    `Output "text" is not defined! Object should has shape {text: string, caretPosition: string | number}. Check the implementation for trigger "${currentTrigger}"\n`
  );
}
```
---
Use case: In my case a custom output is generated outside of the textarea when a selection is made, so I don't want anything to change in the textarea and also remove the trigger character on select.

**Comment by jukben** [comment]
Released as https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v4.7.3
