### ISSUE TITLE
Clicking on second suggestion replaces whole text

### ISSUE THREAD

**Issue by karaxuna** [webscopeio/react-textarea-autocomplete#224]
Type `@first asd @s` and then select second from suggestion in [codepan example](https://codepen.io/karaxuna/pen/abyOyMd)

![tmp](https://user-images.githubusercontent.com/2152815/137109615-5519ef52-2ed4-4077-b646-23e8e97227ce.gif)

**Comment by jukben** [comment]
It's rather workaround – I will definitely revisit it. I assume this is the root cause https://github.com/webscopeio/react-textarea-autocomplete/pull/220

**Comment by karaxuna** [comment]
OK, thanks @jukben

**Comment by karaxuna** [comment]
4.7.3 works fine.
