### ISSUE TITLE
Update React Version

### ISSUE THREAD

**Issue by farzadniazmand** [webscopeio/react-textarea-autocomplete#228]
Please update react version to the newest. On react 17.0.2, I am having conflicting dependency error. Thanks in advance

![image](https://user-images.githubusercontent.com/27675685/143840918-a9e7491f-8c51-43a1-b0b9-c8a9d39858f8.png)

**Comment by jakejakeho-seekers** [comment]
I have created PR: https://github.com/webscopeio/react-textarea-autocomplete/pull/229

**Comment by jukben** [comment]
Should be fixed in https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v4.9.0 Thanks for contribution @jakejakeho-seekers
