### ISSUE TITLE
Provide getters/setters and listener for the caret position

### ISSUE THREAD

**Issue by jukben** [webscopeio/react-textarea-autocomplete#24]
Based on the idea from #23 

It would be nice to provide getter and setter for caret position. 

```js
<ReactTextareaAutocomplete 
    onCaretPositionChange={(position: integer, ref: React$Class) => void}}
    ref={ref => {this.textarea = ref}}
    ...
/>

...

// Getter:

this.textarea.getCaretPosition(): integer;

// Setter:

this.textarea.setCaretPosition(position: integer);
```

We should use our dependency `textarea-caret` as much as possible.

Could help:
https://stackoverflow.com/questions/36978192/how-to-get-text-cursor-position-after-keypress-event-happened

**Comment by marcinlichwala** [comment]
I would like to give it a go :)

**Comment by jukben** [comment]
@marcinlichwala Hi @marcinlichwala! Of course, go for it! Don't hesitate to ask for help. Just mention me in PR and together we'll figure it out for sure.

**Comment by marcinlichwala** [comment]
Hello @jukben,

I'm a bit confused. You mention 'integer' types in the issue description whereas you added the textarea-caret as the recommended dependency. Do you want the methods to return the caret position based on the coordinates or the setSelectionRange type of position? There is already setTextareaCaret method so I believe it might be a duplication.

**Comment by marcinlichwala** [comment]
Created a PR for the integer position (not coordinates).
Still have some issues with one test which I think would be valuable.
https://github.com/webscopeio/react-textarea-autocomplete/pull/28

**Comment by jukben** [comment]
Hey, you are right. But you did it with an ease! I will continue in PR. Good job anyway.

**Comment by jukben** [comment]
Closed by https://github.com/webscopeio/react-textarea-autocomplete/commit/c9e09d6eb79bba0a760a1f8b8e4c2bdfa4835973 💪
