### ISSUE TITLE
Clear Value after using onItemSelected

### ISSUE THREAD

**Issue by maahokgit** [webscopeio/react-textarea-autocomplete#240]
Is there a way to clear the text area after using onItemSelected?

**Comment by jukben** [comment]
I think you can use `onItemSelected` prop and then modify the value of the textarea via ref for example.

**Comment by maahokgit** [comment]
Yea I tried that, looks like it has to do with onChange.

**Comment by maahokgit** [comment]
Figured out a round able way to do it.
