### ISSUE TITLE
Export all Flow-types into separate file called "types.js"

### ISSUE THREAD

**Issue by jukben** [webscopeio/react-textarea-autocomplete#26]
Export all Flow-types into separate file called "types.js", especially from https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L10-L51

**Comment by danilowoz** [comment]
@jukben I would like to take this issue, could you please assign to me?

**Comment by davidsonsns** [comment]
@jukben  I was already typing the same thing hueuhe

**Comment by jukben** [comment]
Thanks, guys, for the interest! @danilowoz you were first, so go on. XD

@davidsonsns Next time ❤️ XD

**Comment by jukben** [comment]
If you are still interested @davidsonsns, you could go for it. 👍

**Comment by davidsonsns** [comment]
Sorry for the delay, I'll start today. Tks :smile:

**Comment by jukben** [comment]
@davidsonsns great, I'm looking forward to your PR. (you could get inspiration from https://github.com/webscopeio/react-textarea-autocomplete/pull/27)

**Comment by jukben** [comment]
close #31
