### ISSUE TITLE
Enable search on autocomplete

### ISSUE THREAD

**Issue by kn4rfy** [webscopeio/react-textarea-autocomplete#46]
Enable searching on the autocomplete

Ex.
you type ':pa' the choices are {'package', 'page'}
then you type ':pac' the choice results is {'package'}

**Comment by jukben** [comment]
Thanks for the issue @kn4rfy. Anyway, I hope, this is out of the scope of this library. This should be done in `dataProvider` function, where you can define whatever behavior you want. See the example for the similar use case. http://react-textarea-autocomplete.surge.sh/

https://github.com/webscopeio/react-textarea-autocomplete#appjs

For sorter implementation, you can use great https://github.com/kentcdodds/match-sorter 💪
