### ISSUE TITLE
Error when try trigger by '['

### ISSUE THREAD

**Issue by marcinziolo** [webscopeio/react-textarea-autocomplete#54]
There is js error during select item when trigger character is "[".

Uncaught SyntaxError: Invalid regular expression: /[\S*$/: Unterminated character class

**Comment by jukben** [comment]
Good catch! We should always escape the trigger char. This should be an easy fix. Are you interested in sending PR? Otherwise, stay tuned I hope I find the time for it this week. 👍

**Comment by jukben** [comment]
Hi @marcinziolo I have good news, this should be fixed in 1.5.3, check it out. 🚀 

Thanks for reporting!
