### ISSUE TITLE
Whitespace in token

### ISSUE THREAD

**Issue by corbt** [webscopeio/react-textarea-autocomplete#58]
Hey there! Thanks so much for this library. I'm trying to use this to implement @ mentions to mention other people. However, since our community works on full names instead of usernames, there is generally a whitespace in the name in question; eg. "Bob Smith". Is there a way I can configure this library to accept one whitespace and pass it on to my dataProvider? Thanks!

**Comment by jukben** [comment]
Hi @corbt! Great issue request. Unfortunately, currently, it's not possible. But I like this use-case I will jump into it and I will try to figure out a solution for it. Stay tuned! 🙏

**Comment by corbt** [comment]
Wow, thanks for the quick work!

Unfortunately I'm running into an issue with testing. After cloning locally and running both `yarn link` commands I'm getting an error `Module not found: Error: Can't resolve '@webscopeio/react-textarea-autocomplete'`. Not sure what's going on with that. :(

**Comment by jukben** [comment]
In the cloned repo you should run `yarn link` and in the target project (in your project I believe) you should be able to run `yarn link @webscopeio/react-textarea-autocomplete` (or something like this, see the output of the previous command). 

Although you can just clone and install the repo, run `yarn dev` and test it in the "example". 👍 

Let me know.

**Comment by corbt** [comment]
FYI I'm on vacation for the next 3 weeks, so I'll have to look at this once I get back. :(

**Comment by jukben** [comment]
@corbt no problem I can wait as soon you are the only one who has requested this feature is crucial to meet your needs. Get back to me after your vacation and enjoy! 🌴

**Comment by jukben** [comment]
It's in master, once you get time to test it out @corbt fell free to get to me with a feedback.
