### ISSUE TITLE
Text touching inserted content is replaced.

### ISSUE THREAD

**Issue by coniel** [webscopeio/react-textarea-autocomplete#61]
Hello, first of all, thank you for this great component! It has been incredibly useful for me. I'm using it as part of a latex editor plugin for draft js. Users can add variables into the latex using @mentions. The issue I'm having is that when a mention is used, any text after it that is not separated by a space, is removed. Here's a gif demonstrating the problem:
![word replaced](https://user-images.githubusercontent.com/1728027/39422747-5a0639cc-4c77-11e8-9893-a8c1f3e7f519.gif)

**Comment by coniel** [comment]
Thanks for the quick reply. Having the option to either replace the entire word or replace the text up to caret would be a simple solution.

Whilst replacing up to the caret as Github's autocomplete does isn't ideal, I think that trying to avoid that would add more complexity to the component than it's worth. I don't think someone moving the caret back and editing the text (as opposed to using a backspace) will be such a common occurrence, and worst case the end result is just a minor inconvenience.

**Comment by jukben** [comment]
So what's your use case? Would you be satisfied with such a solution? I would probably do the same as GitHub. I would replace up to the last word based on last entered character. In your case, it would be just "insert" (in your gif use-case). Is it makes sense for you?

You are using `minChar: 0`, Am I right?

**Comment by coniel** [comment]
Yes, a Github style solution would be fine. I am indeed using `minChar: 0`. Here's another gif demonstrating a more realistic use case. As you can see, when I try and replace the first @foo variable I lose the rest of the content:
![changing variable](https://user-images.githubusercontent.com/1728027/39434069-31f10f60-4ca0-11e8-93a7-c21c349df649.gif)

**Comment by jukben** [comment]
Thanks for the GIF, I will try to come with something ASAP. 👍

**Comment by jukben** [comment]
Hey, @coniel I've finally found some time for this – could you check it out the newest version https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v2.3.2? I hope I was able to fix it quite elegantly and it should work for your use-case well.

**Comment by coniel** [comment]
I owe you long overdue thanks!

I only just had time to upgrade and test it out. It works perfectly. Thank you for fixing #62 as well!

**Comment by jukben** [comment]
Nice! I'm super glad, that I've fixed your case. If you are using React Textarea Autocomplete somewhere where it might have a reason to mention it, create PR for it! I'd be more than happy about it. Cheers!
