### ISSUE TITLE
Show popup only if trigger is after a whitespace (like Github)

### ISSUE THREAD

**Issue by LouisCuvelier** [webscopeio/react-textarea-autocomplete#63]
Hi,

Thanks for this library. It saves me a lot of work 😄  

But, I have a problem. Is it possible to show popup only if trigger is after a whitespace ?
Basically, I want to prevent popup fired when I'm typing something like 
> hello:smile

Instead, I only want to fire popup when there is a space before the trigger, like this:
> hello :smile

Github works like that.

Thanks in advance for your help 😉

**Comment by jukben** [comment]
Hi

I can implement this, but I have to figure out how to configure this. I'd like to keep the components modular and few already existing project relying on the current behavior.

**Comment by LouisCuvelier** [comment]
Maybe a boolean to activate or not the space before ?

**Comment by jukben** [comment]
Yeah, I'm going to introduce such an option for this case. 👍

**Comment by jukben** [comment]
Hey! @LouisCuvelier you can try to install the version from the master. The deploy will be soon. (this week I hope). Hope you like it!

**Comment by LouisCuvelier** [comment]
Juste perfect ! Thanks 😄
