### ISSUE TITLE
Possible IE issue with an Event object

### ISSUE THREAD

**Issue by jvorcak** [webscopeio/react-textarea-autocomplete#64]
I'm trying to create a higher abstraction on top of this awesome plugin. Something not that low level - OOTB solution with support for emojis & markdown.

However, in IE I experience this issue.

Steps to reproduce:
1) Clone https://github.com/webscopeio/react-markdown-editor
2) `yarn` && `yarn start`
3) In a second terminal, `cd example && yarn && yarn start`
4) Open page in IE11

I've included `babel-polyfill` in my example project.

![bug](https://user-images.githubusercontent.com/1083817/39962460-788f77a0-564f-11e8-80ab-a31f5e016a43.gif)

**Comment by jukben** [comment]
We are using Babel preset from CRA https://github.com/facebook/create-react-app/tree/next/packages/babel-preset-react-app 

Object.entries is not polyfilled by default and it should be polyfilled manually.
https://github.com/facebook/create-react-app/issues/1856

But `babel-polyfill` should be enough to do so. How did you include it?
