### ISSUE TITLE
The doc about trigger option `output`  does not match actual code.

### ISSUE THREAD

**Issue by oklas** [webscopeio/react-textarea-autocomplete#67]
The doc about trigger option `output`  does not match actual code.

The doc says that item must be unique. And the item unique id is received as result of calling function specified in trigger option `output`. This function must return object with optional field named `key` wich will be considered as item unique id. Doc declares a prototype:

```js
      output?: (
        item: Object | string,
        trigger?: string
      ) =>
        | {|
            key?: ?string,
            text: string,
            caretPosition: "start" | "end" | "next" | number
          |}
        | string,
```

But the code currently ignore field `key` from object returned by this function. Same time code 
actually use field `key` of `item` itself instead of result of that function in the line:

https://github.com/webscopeio/react-textarea-autocomplete/blob/7bd61f93c572cdf7af4f3de1409d8fc2fd1a5816/src/List.jsx#L58

**Comment by jukben** [comment]
Great catch!

**Comment by jukben** [comment]
Released https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v2.2.1 

Thanks 🙏

**Comment by oklas** [comment]
Thank you too for great work on this library and for quick accept merge and release!
