### ISSUE TITLE
Scroll item to stay always in the viewport (when list is set to overflow for example)

### ISSUE THREAD

**Issue by monochromer** [webscopeio/react-textarea-autocomplete#70]
How to scroll a height-limited list with options when they get in focus?

**Comment by jukben** [comment]
Hi, could you please be more specific? Do you want to limit the autocomplete options and make them scrollable? Then you need to provide your own styles. The defaults one don't handle this case.

Something like this: https://codepen.io/jukben/pen/erwRbr?editors=0110?

**Comment by monochromer** [comment]
I want clicking on the arrow up and down, the list was scrolled until the element got the focus

**Comment by jukben** [comment]
Got it. This could be easily fixed with https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView. In the case when `rta__list` has `overflow: scroll` with it we can ensure that element is still in the view. 👍 

Are you interested in sending PR for it?

**Comment by monochromer** [comment]
Thanks!
I don't think I'll have time to learn source code for PR.

**Comment by jukben** [comment]
OK. I hope I will do it soon, it should be quite straightforward.

**Comment by monochromer** [comment]
Thanks for this feature! 
I think for UX this settings would be better for moving to next item
```js
scrollIntoView({
  behavior: 'smooth',
  block: 'end'
 });
```
and
```js
scrollIntoView({
  behavior: 'smooth',
  block: 'start'
 });
```
for moving to previous item

**Comment by jukben** [comment]
That actually makes a sense! Good point. I will try to cook it up.

**Comment by jukben** [comment]
@monochromer feel free to test https://github.com/webscopeio/react-textarea-autocomplete/releases/tag/v2.3.0
