### ISSUE TITLE
What's new in v2?

### ISSUE THREAD

**Issue by kajmagnus** [webscopeio/react-textarea-autocomplete#71]
Hi! I was thinking about upgrading, in case of bugs & security fixes, and noticed that now there's a v2.2.2 — I'm using v1.4.x. I didn't find any changelog or release notes for 1.5 or 2.x — are they available somewhere or maybe if you have time would you like to write a bit about what's changed? can I upgrade from 1.4 to 2.2.2 without errors? or maybe I need to rewrite how I use react-texta.-autoc.?

**Comment by jukben** [comment]
Hi, sorry about it, you should be totally fine. There is the breaking change https://github.com/webscopeio/react-textarea-autocomplete/commit/bff575a1b9e66bd69a21fa1671433480e5afb3f7

I'll update the release log – I started to write them recently 🤓
