### ISSUE TITLE
Whether Chrome browser is not supported

### ISSUE THREAD

**Issue by fanlyze** [webscopeio/react-textarea-autocomplete#72]
Chrome browser's version is 68.0.3440.7.
![20180611004713](https://user-images.githubusercontent.com/35338391/41203996-8f15ea44-6d11-11e8-8e22-9f943b263fad.png)

**Comment by jukben** [comment]
Could you please try a different browser? This looks like an issue with Unicode characters on your machine, not with the package itself. (it's just matter of implementation of provider function.)

**Comment by fanlyze** [comment]
It works in Firefox. so,how do I solve this problem in Chrome? @jukben

**Comment by jukben** [comment]
Could you please try this page? http://getemoji.com/ I'm afraid it's bug in your Chrome and thus is completely unrelated with the package.

**Comment by fanlyze** [comment]
@jukben I open http://getemoji.com/ with chrome.
![20180611232346](https://user-images.githubusercontent.com/35338391/41241085-b0862b40-6dce-11e8-98ba-57069439d68e.png)
This is the question of my chrome browser.

**Comment by jukben** [comment]
That's very weird. I would recommend you to reinstall the Chrome.
