### ISSUE TITLE
Custom callback-based trigger

### ISSUE THREAD

**Issue by glimow** [webscopeio/react-textarea-autocomplete#77]
This looks like a very nicely done component. I wondered if there is a more general way to trigger an autocomplete than using string matching, like a function that would take current text and caret position and returns a boolean e.g.
```javascript
 trigger: (text, caretPosition) => {
   // some code that computes if autocomplete should trigger or not
}
```
As I want to provide grammar-based autocomplete rather than character-based one.

**Comment by jukben** [comment]
That's actually interesting idea. I will try to play with it and come up with some solution. 👍

**Comment by glimow** [comment]
Thanks for the answer, that's awesome ! I'll definitely keep an eye on this

**Comment by jukben** [comment]
Hey, @glimow could you please elaborate more how you're thinking about this feature?

Let's say that I will create such a prop, but right now for example trigger character has relation to `dataProvider`. With your approach, I can only decide when to open the autocomplete, but which data should I load?

It probably doesn't make a sense to have such a possibility bound to some trigger char, right?

**Comment by jukben** [comment]
Ping @glimow 😸

**Comment by jukben** [comment]
Closing for now for inactivity.
