### ISSUE TITLE
ERROR in index-5353b33322ce416969f9.js from UglifyJs

### ISSUE THREAD

**Issue by fanlyze** [webscopeio/react-textarea-autocomplete#80]
When i use react-textarea-autocomplete like the demo, there is a error. That is the error of webpack to build:
ERROR in index-5353b33322ce416969f9.js from UglifyJs
Invalid assignment [index-5353b33322ce416969f9.js:6835,89]

Whether the use of "import emoji from "@jukben/emoji-search"" does't support “new webpack.optimize.UglifyJsPlugin(),”

**Comment by jukben** [comment]
Thanks for reporting! This was actually issue with my different library, fixed here https://github.com/jukben/emoji-search/releases/tag/v1.1.6

**Comment by fanlyze** [comment]
Hi @jukben 
When i used v1.1.6, there was another problem. It can't load emoji:
![default](https://user-images.githubusercontent.com/35338391/43654320-6ec984f8-977d-11e8-85cd-ae76a74403a0.png)

![default](https://user-images.githubusercontent.com/35338391/43654369-9436ae6e-977d-11e8-9449-ee6f6c453ccc.png)

**Comment by jukben** [comment]
Ah, sorry @fanlyze install version 1.1.7, I did refactor 👍 Should be fine now.
