### ISSUE TITLE
Including Trigger in selection output breaks functionality

### ISSUE THREAD

**Issue by audiolion** [webscopeio/react-textarea-autocomplete#84]
Hello 👋 ,

If you have a trigger like `@` which opens up a list of users to select from, and the output is `@audiolion`, if you try to do another `@` in the same textarea and select `@webscopeio`, the selection will *replace* the first `@audiolion` with `@webscopeio` instead of inserting the new autocomplete.

Seems fairly obvious that it looks for the first occurrence of the trigger in the document and replaces instead of maintaining the current selection of where the trigger occurred and replacing it there.

**Comment by jukben** [comment]
Hi! Thanks for the bug report, could you please create repro demo (you can use this pen as a start https://codepen.io/jukben/pen/bYZqvR)?

**Comment by audiolion** [comment]
@jukben oh man, awesome codepen starter, here is a repro: https://codepen.io/yankasuto/pen/WgyObR

Try inserting two autocompletes in a row and you will see it happen

My apologies, you have to have "allowWhitespace: true" for the bug to occur.

**Comment by jukben** [comment]
Great! I see, that's actually feature because `allowWhitespace: true`, why do you need it in the first time?

**Comment by jukben** [comment]
Great! I see, that's actually a feature because allowWhitespace: true, why do you need it in the first time?

allowWhitespace is there for a reason if your tokens are with space, so you want to replace all occurrences no matter whitespaces.

**Comment by jukben** [comment]
Great! I see, that's actually a feature because allowWhitespace: true, why do you need it in the first time?

`allowWhitespace` is there for a reason if your tokens are with a space, so you want to replace all the occurrences no matter whitespaces.

**Comment by jukben** [comment]
Great! I see, that's actually a feature because `allowWhitespace: true`, why do you event need it?

`allowWhitespace` is there for a reason if your tokens are with a space, so you want to replace all the occurrences no matter whitespaces.

**Comment by audiolion** [comment]
Ok I made a gif of using the codepen, you are saying this is the intended behavior:

![](https://media.giphy.com/media/fGI4c8TGI2yASbw3lU/giphy.gif)

If it is then you can close this issue. To me it makes it so you can never have two of the same autocomplete items in the same text area.

**Comment by jukben** [comment]
Oh, I see, that's definitely buggy. I mean, the best you can do is to avoid `allowWhitespace` at all, but since it's there I will do my best to fix it.

![rta_fix_whitespace](https://user-images.githubusercontent.com/8135252/45551251-905f3d80-b82d-11e8-8fb1-da4c6b8624d9.gif)

This looks fine, don't you say?

**Comment by audiolion** [comment]
Yeah I actually am avoiding `allowWhitespace` currently. That fix looks good!
