### ISSUE TITLE
Scrolled down text area causes auto-complete list to appear out of alignment

### ISSUE THREAD

**Issue by jtokoph** [webscopeio/react-textarea-autocomplete#86]
![screen shot 2018-09-28 at 12 03 56](https://user-images.githubusercontent.com/346225/46228353-af25ff80-c316-11e8-883a-7f787d7c806c.png)

The title and screenshot should explain most of the problem.

I would expect that even while scrolled down in the text area that the auto-complete options would still appear in-line with the cursor.

**Comment by jukben** [comment]
Thanks for the issue, that's definitely a bug I'm going to fix this ASAP.

**Comment by jtokoph** [comment]
It seems like it's just off by `scrollTop` but I would have thought the cursor library being used would have this figured out. I've worked around it myself by just auto-resizing the textarea to expand and never scroll.

**Comment by jukben** [comment]
Hey @jtokoph! I've just released the new version which has fixed this issue. As you can check it out here: https://codepen.io/jukben/pen/bYZqvR. Hope you like it! 🚀
