### ISSUE TITLE
Feature request: IDE like auto suggest

### ISSUE THREAD

**Issue by obiwarn** [webscopeio/react-textarea-autocomplete#88]
I desperately search for a function like this:

1. no trigger char (any char in the auto suggest list opens suggestions)
2. filter suggest list by what is typed (types ja => only show "java" and "jabber" in the list)

Is it hard to implement sth. like this?

![image](https://i.stack.imgur.com/k9FX0.gif)

**Comment by jukben** [comment]
I guess this is out of the scope of this library. 😞
