### ISSUE TITLE
Refactor: componentWillReceiveProps deprecation

### ISSUE THREAD

**Issue by O4epegb** [webscopeio/react-textarea-autocomplete#89]
Since `componentWillReceiveProps` hook is deprecated, consider other options? https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by jukben** [comment]
I know about it, I'd be more than happy to accept a PR for this. 👍

**Comment by jukben** [comment]
Adressed in https://github.com/webscopeio/react-textarea-autocomplete/pull/90
