### ISSUE TITLE
Multi character trigger?

### ISSUE THREAD

**Issue by O4epegb** [webscopeio/react-textarea-autocomplete#91]
I see that it is not possible to use this library with multi character trigger. Could it be implemented in the future or is it out of scope?

I am already using it for mentions, but current use case is commands, for example, first you type `/` and get list of commands, then after selecting one, for example `/kick` you get list with all chat members.

**Comment by jukben** [comment]
Interesting idea and good example use case, I'll think about it. 👍

**Comment by jukben** [comment]
Hey, just to let you know I started to work on this and it seems it should be relatively easy. I have to check for potential corner cases, but eventually, I would be able possible. I'll keep this thread up to date. 💪

**Comment by O4epegb** [comment]
Oh, that's actually very nice, thank you!

**Comment by jukben** [comment]
Hey, @O4epegb I've just deployed new version 3.1.1 which should solve your issue.

Check out this: https://codepen.io/jukben/pen/aQmLZG (type `/` to start)

What do you say about it?
