### ISSUE TITLE
Debounce dataProvider for remote data

### ISSUE THREAD

**Issue by superandrew213** [webscopeio/react-textarea-autocomplete#96]
Performing server lookups on every letter change might not be necessary. Receiving the delayed results one after another doesn't look that nice either.

What do you think about adding an option to debounce dataProvider?

Another option would be to provide a `results` prop and a `onTokenChange` prop? This way we can have more control.

Or maybe I am missing something and you can already do this.

**Comment by superandrew213** [comment]
I got it to work using `debounce-promise`. Lodash.debounce was not working properly.

**Comment by jukben** [comment]
Yeah! The data provider is able to eat Promise, so it should be fine to use whatever solution you might like.

**Comment by anton6** [comment]
@superandrew213 can you please share a code snippet with the `debounce-promise`. In my case what sees to happen is it stacks all the calls to `dataProvider` and calls them all after the debounce period.

**Comment by anton6** [comment]
The problem was on my end, I was playing with `react-textarea-autocomplete` inside of react-styleguidst code snippet which triggers re-render on every update.

**Comment by soumen-roy-001** [comment]
Here is one example where dataProvider uses lodash debounce to fetch the searched users but not working - https://codesandbox.io/p/sandbox/reacttextareaautocomplete-forked-543p8y

![Image](https://github.com/user-attachments/assets/feed85be-d223-49ba-9286-587cd6df4055)

Without setTimeout or debounce means with every keystroke it seems working

**Comment by soumen-roy-001** [comment]
Regarding my above comment - https://github.com/webscopeio/react-textarea-autocomplete/issues/96#issuecomment-2595311237 I have come up with some workarounds with the same codesandbox example link i.e., https://codesandbox.io/p/sandbox/reacttextareaautocomplete-forked-543p8y

Two possible ways I have found: 

1. classic debounce method which can support `trailing` and `leading` options as in lodash/debounce
2. modified `debounce-promise` source code named as `debounce-promise-local.js`
